/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticket;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class GUI extends javax.swing.JFrame {
    public static LinkedList <MovieTicket>  billList = new LinkedList <MovieTicket>();

    /**
     * Creates new form GUI
     */
         public static void writeFile()throws IOException
 {
   FileWriter tulis = new FileWriter ("Bills.txt");
   PrintWriter teks = new PrintWriter (tulis);
teks.printf("%-15s%-15s%-15s%-25s%-15s%-25s%-10s%-20s%-20s%-15s%n", "Customer Name","Customer Type","Phone Number","Booking Day","Movie","Number Of Ticket","Time","Number of seats","Payment per Ticket","Total Payment");   
   for(MovieTicket s: billList)
   teks.write (s.toStringForFile());
     //teks.write (3.toStringForFile ());
    tulis.close ();
 } 
    public static void readFile () throws IOException{
        
    
   File inFile = new File ("Bills.txt");
   Scanner scanner = new Scanner (inFile);
   while (scanner.hasNextLine ()) { //check if there are more line
    String line =scanner.nextLine ();
    outputTA.append (line + "\n");
   }//akan dpt error, tasalary not static, cannot be referred to static variable. so
                              //zight click properties tasalary, code, chopose static
   scanner.close ();
    }
    
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);//display frame in center
        date();
    }
     public void date(){
        Date dateT = new Date();
        SimpleDateFormat date2 = new SimpleDateFormat("dd-MM-yyyy");
        String add = date2.format(dateT);
        date.setText(add);
    }//display the live date 
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        unchartedRB = new javax.swing.JRadioButton();
        memoryRB = new javax.swing.JRadioButton();
        furyRB = new javax.swing.JRadioButton();
        infiniteRB = new javax.swing.JRadioButton();
        homefrontRB = new javax.swing.JRadioButton();
        greenlandRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        dayCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        timeCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        customerCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ticketNoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seatNoTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        chargeTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalPaymentTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        calculateBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        displayAllBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        editBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        dateTM = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMA TICHET SYSTEM");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        jLabel1.setText("CINEMA TICKET SYSTEM");

        panel.setBackground(new java.awt.Color(0, 153, 153));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel2.setText("Name");

        jLabel3.setText("Movie");

        buttonGroup1.add(unchartedRB);
        unchartedRB.setText("Uncharted");

        buttonGroup1.add(memoryRB);
        memoryRB.setText("Memory");

        buttonGroup1.add(furyRB);
        furyRB.setText("Fury");

        buttonGroup1.add(infiniteRB);
        infiniteRB.setText("Infinite");

        buttonGroup1.add(homefrontRB);
        homefrontRB.setText("Homefront");

        buttonGroup1.add(greenlandRB);
        greenlandRB.setText("Greenland");

        jLabel4.setText("Day");

        dayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));

        jLabel5.setText("Time");

        timeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2:00pm", "7:00pm", "10:00pm" }));

        jLabel10.setText("Customer Type");

        customerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Student", "Staff" }));

        jLabel6.setText("Number of ticket");

        jLabel7.setText("Seat's Number");
        jLabel7.setToolTipText("");

        jLabel8.setText("Payment per ticket");

        jLabel9.setText("Total Payment");

        jLabel11.setText("Phone Number");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unchartedRB)
                                    .addComponent(infiniteRB)
                                    .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(homefrontRB)
                                            .addComponent(memoryRB))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(greenlandRB)
                                            .addComponent(furyRB)))))
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chargeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(totalPaymentTF))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(customerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(unchartedRB)
                        .addComponent(memoryRB)
                        .addComponent(furyRB)
                        .addComponent(ticketNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infiniteRB)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homefrontRB)
                        .addComponent(greenlandRB)
                        .addComponent(jLabel7)
                        .addComponent(seatNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(timeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(chargeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalPaymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        calculateBTN.setText("Calculate");
        calculateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBTNActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        displayAllBTN.setText("Display All");
        displayAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        editBTN.setText("Edit");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        dateTM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dateTM.setText("Date:");

        date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(dateTM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(calculateBTN)
                                .addGap(18, 18, 18)
                                .addComponent(saveBTN)
                                .addGap(18, 18, 18)
                                .addComponent(displayAllBTN)
                                .addGap(18, 18, 18)
                                .addComponent(searchBTN)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBTN)
                                .addGap(18, 18, 18)
                                .addComponent(editBTN)
                                .addGap(63, 63, 63)
                                .addComponent(resetBTN)
                                .addGap(18, 18, 18)
                                .addComponent(exitBTN))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date)
                        .addComponent(dateTM))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateBTN)
                    .addComponent(saveBTN)
                    .addComponent(displayAllBTN)
                    .addComponent(searchBTN)
                    .addComponent(deleteBTN)
                    .addComponent(editBTN)
                    .addComponent(resetBTN)
                    .addComponent(exitBTN))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBTNActionPerformed
     try{  
        String bookingDay = (String) dayCB.getSelectedItem ( ) ;
        String customerType= (String) customerCB.getSelectedItem ( ) ;
        int NoOfTicket=Integer.parseInt(ticketNoTF.getText());
        Calculation calculate = new Calculation(bookingDay,  customerType,  NoOfTicket);
        double PaymentPerTicket=calculate.PaymentPerticket(bookingDay, customerType);
        double totalPayment=calculate.totalPaymen(PaymentPerTicket);
        chargeTF.setText("\n" +String.format ("%.2f", PaymentPerTicket));
        totalPaymentTF.setText("\n" +String.format ("%.2f", totalPayment));
    }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in Interger format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }

    }//GEN-LAST:event_calculateBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
     try{  
         String customerName = nameTF.getText ();
     
        String bookMovie = null;
        if (unchartedRB.isSelected()) {
        bookMovie = "Uncharted";
        } 
        else if  (memoryRB.isSelected()){
        bookMovie = "Memory";}
        else if  (furyRB.isSelected()){
        bookMovie = "Fury";}
        else if  (infiniteRB.isSelected()){
        bookMovie = "Infinite";}
        else if  (homefrontRB.isSelected()){
        bookMovie = "Homefront";}
        else{
            bookMovie = "greenland";
        }
        String bookingDay = (String) dayCB.getSelectedItem ( ) ;
        String bookTime = (String) timeCB.getSelectedItem ( ) ;
        String PhoneNumber = phoneTF.getText ();
        String customerType= (String) customerCB.getSelectedItem ( ) ;
        int NoOfTicket=Integer.parseInt(ticketNoTF.getText());
        String numOfSeats=seatNoTF.getText ();
        double payemtPerTicket=Double.parseDouble(chargeTF.getText());
        double totalPayment= Double.parseDouble(totalPaymentTF.getText());
        MovieTicket bill=new MovieTicket( customerName,customerType,PhoneNumber,bookingDay,bookMovie,NoOfTicket,bookTime,numOfSeats,payemtPerTicket,totalPayment);
          billList.add(bill);
          outputTA.setText(bill.toString());
            JOptionPane.showMessageDialog(null, "Data is saved.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

            writeFile();
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in Integer format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        
      
        } 
    }//GEN-LAST:event_saveBTNActionPerformed

    private void displayAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBTNActionPerformed
        try{
            readFile ();
        }catch (IOException e) {
            System.out.println (e.getMessage ()) ;
        }
    }//GEN-LAST:event_displayAllBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        nameTF.setText ("");
        ticketNoTF.setText ("");
        phoneTF.setText ("");
        seatNoTF.setText ("");
        chargeTF.setText ("");
        totalPaymentTF.setText ("");
        dayCB.setSelectedIndex (0);
        timeCB.setSelectedIndex (0);
        customerCB.setSelectedIndex (0);
        buttonGroup1.clearSelection();
        outputTA.setText ("");
    }//GEN-LAST:event_resetBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        String output=null;
        boolean found=false;
        File input=new File("Bills.txt");
        FileReader fr=null;
        Scanner ob=new Scanner(System.in);
        String searchWord,str;
        searchWord = JOptionPane.showInputDialog ("Enter the costomer name you want to search for:");
        try{
    fr=new FileReader (input);
    BufferedReader br=new BufferedReader (fr);
    while ( (str=br.readLine ()) !=null) {
        if (str.contains (searchWord)){
            String[] parts = str.split("\\s+");
            for (int i = 0; i < parts.length; i++) {
                nameTF.setText(parts[0]);
                phoneTF.setText(parts[2]);
                ticketNoTF.setText(parts[5]);
                seatNoTF.setText(parts[7]);
               chargeTF.setText(parts[8]);
                totalPaymentTF.setText(parts[9]);
                 customerCB.setSelectedItem(parts[1]);
                  dayCB.setSelectedItem(parts[3]);
                   timeCB.setSelectedItem(parts[6]);
                if (parts[4].equalsIgnoreCase("Uncharted")) {
                unchartedRB.setSelected (true);
                }
                else if (parts[4].equalsIgnoreCase("Memory")) {
                memoryRB.setSelected (true);
                }
                else if (parts[4].equalsIgnoreCase("Fury")) {
                furyRB.setSelected (true);
                }
                else if (parts[4].equalsIgnoreCase("Infinite")) {
                infiniteRB.setSelected (true);
                }
                else if (parts[4].equalsIgnoreCase("Homefront")) {
                homefrontRB.setSelected (true);
                }               
               else {
               greenlandRB.setSelected (true);}
                
             output=parts[0]+"\t"+"\t"+parts[1]+"\t"+parts[2]+"\t"+parts[3]+"\t"+parts[4]+"\t"+parts[5]+"\t"+"\t"+parts[6]+"\t"+parts[7]+"\t"+"\t"+parts[8]+"\t"+"\t"+parts[9];
                
              
            }
            outputTA.setText("Customer Name\tCustomer Type\tPhone Number\tBooking Day\tMovie\tNumber Of Ticket\tTime\tNumber of seats\tPayment per Ticket\tTotal Payment\n");
            outputTA.append(output);
           found=true;
          
        }
       
    }
    if(found==false){
        JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); }
             
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); 
        } catch (IOException ex) {
            JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); 
        }
        finally{
            try {
                fr.close ();
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    
    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        int index;
        boolean found =false;
        String delete = JOptionPane.showInputDialog ("Enter the name of the customer to delete for:");
        for (MovieTicket d:billList) {
          if (d.getCustomerName().equals(delete)){
          index = billList.indexOf(d);//indexOf s object in the students arraylist
          
          billList.remove(index);//remove object from arrayList
          try{
        writeFile();
         }catch (Exception e) {
         System.out.println (e.getMessage ()) ;
         }
          JOptionPane.showMessageDialog(null, "The file is deleted successfully.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);          found=true;
          break;
           }//if  
         }//for
        if(found==false)   
          JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE);     
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
       try{  
         String customerName= nameTF.getText ();
     
        String bookMovie = null;
        if (unchartedRB.isSelected()) {
        bookMovie = "Uncharted";
        } 
        else if  (memoryRB.isSelected()){
        bookMovie = "Memory";}
        else if  (furyRB.isSelected()){
        bookMovie = "Fury";}
        else if  (infiniteRB.isSelected()){
        bookMovie = "Infinite";}
        else if  (homefrontRB.isSelected()){
        bookMovie = "Homefront";}
        else{
            bookMovie = "greenland";
        }
        String bookingDay = (String) dayCB.getSelectedItem ( ) ;
        String bookTime = (String) timeCB.getSelectedItem ( ) ;
        String PhoneNumber = phoneTF.getText ();
        String customerType= (String) customerCB.getSelectedItem ( ) ;
        int NoOfTicket=Integer.parseInt(ticketNoTF.getText());
        String numOfSeats=seatNoTF.getText ();
        double payemtPerTicket=Double.parseDouble(chargeTF.getText());
        double totalPayment= Double.parseDouble(totalPaymentTF.getText());
        MovieTicket bill=new MovieTicket( customerName,customerType,PhoneNumber,bookingDay,bookMovie,NoOfTicket,bookTime,numOfSeats,payemtPerTicket,totalPayment);
          billList.add(bill);
                      writeFile();
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in Integer format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
           int index;
        boolean found =false;
       String customerName= nameTF.getText ();
        for (MovieTicket de:billList) {
          if (de.getCustomerName().equalsIgnoreCase(customerName)){
          index = billList.indexOf(de);//indexOf s object in the bills arraylist
          
          billList.remove(index);//remove object from arrayList
          try{
        writeFile();
         }catch (Exception e) {
         System.out.println (e.getMessage ()) ;
         }
          JOptionPane.showMessageDialog(null, "The file is edited successfully.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);          found=true;
          break;
           }//if  
         }//for
        if(found==false)   
          JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); 
    }//GEN-LAST:event_editBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
         System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateBTN;
    private javax.swing.JTextField chargeTF;
    private javax.swing.JComboBox<String> customerCB;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateTM;
    private javax.swing.JComboBox<String> dayCB;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayAllBTN;
    private javax.swing.JButton editBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JRadioButton furyRB;
    private javax.swing.JRadioButton greenlandRB;
    private javax.swing.JRadioButton homefrontRB;
    private javax.swing.JRadioButton infiniteRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton memoryRB;
    private javax.swing.JTextField nameTF;
    private static javax.swing.JTextArea outputTA;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField seatNoTF;
    private javax.swing.JTextField ticketNoTF;
    private javax.swing.JComboBox<String> timeCB;
    private javax.swing.JTextField totalPaymentTF;
    private javax.swing.JRadioButton unchartedRB;
    // End of variables declaration//GEN-END:variables
}
