/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricitybill.project;

/**
 *
 * @author rayan
 */
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI extends javax.swing.JFrame {
    public static ArrayList <Electricity>  billList = new ArrayList <Electricity>();

    /**
     * Creates new form GUI
     */
       public static void writeFile()throws IOException
 {
   FileWriter tulis = new FileWriter ("Bills.txt");
   PrintWriter teks = new PrintWriter (tulis);
   teks.printf("%-15s%-15s%-15s%-25s%-10s%-10s%-10s%-15s%-15s%-15s%n", "AcoountNO","Owner Name", "Date", "Address", "Arrears", "PMR", "CMR","Total Unit","Current Charge","Total Bill");
   
   for(Electricity s: billList)
   teks.write (s.toStringForFile());
     //teks.write (3.toStringForFile ());
    tulis.close ();
 } 
    public static void readFile () throws IOException{
        
    
   File inFile = new File ("Bills.txt");
   Scanner scanner = new Scanner (inFile);
   while (scanner.hasNextLine ()) { //check if there are more line
    String line =scanner.nextLine ();
    outputTA.append (line + "\n");
   }//akan dpt error, tasalary not static, cannot be referred to static variable. so
                              //zight click properties tasalary, code, chopose static
   scanner.close ();
    }
    public GUI() {
        initComponents();
         setLocationRelativeTo(null);//display frame in center
         date();
    }
    public void date(){
        Date dateT = new Date();
        SimpleDateFormat date2 = new SimpleDateFormat("dd-MM-yyyy");
        String add = date2.format(dateT);
        dateTM.setText(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        calculateBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        diplayBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numberTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dayCB = new javax.swing.JComboBox<>();
        monthCB = new javax.swing.JComboBox<>();
        yearCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adressTA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        arrearsTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pmrTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmrTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalUnitTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        currentChargeTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalBillTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateTM = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        editBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRICITY BILLING SYSTEM");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ELECTRiCITY BILLING SYSTEM");

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        calculateBTN.setText("Calculate");
        calculateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBTNActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        diplayBTN.setText("Display All");
        diplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diplayBTNActionPerformed(evt);
            }
        });

        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel2.setText("Account Number");

        jLabel3.setText("Bill Date");

        dayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        monthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthCBActionPerformed(evt);
            }
        });

        yearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2020", "2021", "2022", "2023", "2024" }));

        jLabel4.setText("Owner Name");

        jLabel5.setText("Owner Adress");

        adressTA.setColumns(20);
        adressTA.setRows(5);
        jScrollPane1.setViewportView(adressTA);

        jLabel6.setText("Arrears");

        jLabel7.setText("Previous Meter Reading");

        pmrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmrTFActionPerformed(evt);
            }
        });

        jLabel8.setText("Current Meter Reading");

        jLabel9.setText("Total Unit");

        jLabel10.setText("Current Charge");

        jLabel11.setText("Total Bill");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numberTF)
                            .addComponent(nameTF)
                            .addComponent(jScrollPane1))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pmrTF, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(cmrTF)
                            .addComponent(totalUnitTF)
                            .addComponent(currentChargeTF)
                            .addComponent(totalBillTF))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(arrearsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pmrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(totalUnitTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(currentChargeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(totalBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(arrearsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Date");

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        editBTN.setText("Edit");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(calculateBTN)
                .addGap(18, 18, 18)
                .addComponent(saveBTN)
                .addGap(18, 18, 18)
                .addComponent(diplayBTN)
                .addGap(13, 13, 13)
                .addComponent(searchBTN)
                .addGap(18, 18, 18)
                .addComponent(deleteBTN)
                .addGap(18, 18, 18)
                .addComponent(editBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBTN)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(dateTM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(dateTM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resetBTN)
                        .addComponent(exitBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calculateBTN)
                        .addComponent(saveBTN)
                        .addComponent(diplayBTN)
                        .addComponent(deleteBTN)
                        .addComponent(searchBTN)
                        .addComponent(editBTN)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pmrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmrTFActionPerformed

    private void monthCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthCBActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        nameTF.setText ("");
        numberTF.setText ("");
        adressTA.setText ("");
        arrearsTF.setText ("");
        pmrTF.setText ("");
        cmrTF.setText ("");
        totalUnitTF.setText ("");
        currentChargeTF.setText ("");
        totalBillTF.setText ("");
        outputTA.setText ("");
        dayCB.setSelectedIndex (0);
        monthCB.setSelectedIndex (0);
        yearCB.setSelectedIndex (0);
    }//GEN-LAST:event_resetBTNActionPerformed

    private void diplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diplayBTNActionPerformed
        try{
            readFile ();
        }catch (IOException e) {
            System.out.println (e.getMessage ()) ;
        }
    }//GEN-LAST:event_diplayBTNActionPerformed

    private void calculateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBTNActionPerformed
        try{
            double pmr=Double.parseDouble(pmrTF.getText());
            double cmr=Double.parseDouble(cmrTF.getText());
            double arrears=Double.parseDouble(arrearsTF.getText());
            Calculation calculate = new Calculation(arrears,  pmr,  cmr);
            double totalUnit=calculate.totalUnit(cmr, pmr);
            double currentCharge=calculate.CurrentCahrge(totalUnit);
            double totalBill=calculate.totalBill(arrears, currentCharge);
            totalUnitTF.setText("\n" +String.format (" %.2f", totalUnit));
            currentChargeTF.setText("\n" +String.format ("%.2f", currentCharge));
            totalBillTF.setText("\n" +String.format ("%.2f", totalBill));
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in double format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_calculateBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        try{
            int accountNO = Integer.parseInt (numberTF.getText());
            String date =" ";
            int monthInt=0;
            String month = (String) monthCB.getSelectedItem ( ) ;
            switch (month) {
                case "January": monthInt = 1;break;
                case "February": monthInt = 2;break;
                case "March": monthInt = 3;break;
                case "April": monthInt = 4;break;
                case "May": monthInt = 5;break;
                case "June": monthInt = 6;break;
                case "July": monthInt = 7;break;
                case "August": monthInt= 8;break;
                case "September": monthInt= 9;break;
                case "October": monthInt = 10;break;
                case "November": monthInt =11;break;
                case "December": monthInt = 12;break;
            }
            date=dayCB.getSelectedItem() +"/" +monthInt +"/" + (String) yearCB.getSelectedItem();
            String name = nameTF.getText ();
            String address = adressTA.getText ();
            double arrears=Double.parseDouble(arrearsTF.getText());
            double pmr=Double.parseDouble(pmrTF.getText());
            double cmr=Double.parseDouble(cmrTF.getText());

            double totalUnit=Double.parseDouble(totalUnitTF.getText());
            double currentCharge=Double.parseDouble(currentChargeTF.getText());
            double totalBill=Double.parseDouble(totalBillTF.getText());

            Electricity bill=new Electricity( accountNO, name,  address,  date,   arrears,  pmr,  cmr, totalUnit, currentCharge, totalBill);
            billList.add(bill);
            outputTA.setText(bill.toString());
            JOptionPane.showMessageDialog(null, "Data is saved.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

            writeFile();
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in Integer format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }

    }//GEN-LAST:event_saveBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        int index;
        boolean found =false;
        String delete = JOptionPane.showInputDialog ("Enter the account number of the customer to delete for:");
        int accountNo=Integer.parseInt(delete);
        for (Electricity d:billList) {
          if (d.getAcountNo()==accountNo){
          index = billList.indexOf(d);//indexOf s object in the bills arraylist
          
          billList.remove(index);//remove object from arrayList
          try{
        writeFile();
         }catch (Exception e) {
         System.out.println (e.getMessage ()) ;
         }
          JOptionPane.showMessageDialog(null, "The file is deleted successfully.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);          found=true;
          break;
           }//if  
         }//for
        if(found==false)   
          JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE);  
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        String output=null;
        boolean found=false;
        File input=new File("Bills.txt");
        FileReader fr=null;
        Scanner ob=new Scanner(System.in);
        String searchWord,str;
        searchWord = JOptionPane.showInputDialog ("Enter the account number you want to search for:");
        try{
    fr=new FileReader (input);
    BufferedReader br=new BufferedReader (fr);
    while ( (str=br.readLine ()) !=null) {
        if (str.contains (searchWord)){
            String[] parts = str.split("\\s+");
            for (int i = 0; i < parts.length; i++) {
                numberTF.setText(parts[0]);
                nameTF.setText(parts[1]);
                String date1=parts[2];
                adressTA.setText(parts[3]);
                arrearsTF.setText(parts[4]);
                pmrTF.setText(parts[5]);
                cmrTF.setText(parts[6]);
                totalUnitTF.setText(parts[7]);
                currentChargeTF.setText(parts[8]);
                totalBillTF.setText(parts[9]);
                String[] date = date1.split("/");
                for (int j = 0; j < date.length; j++) {
                    int day= Integer.parseInt (date[0]);
                    dayCB.setSelectedIndex (day);
                    int month=Integer.parseInt (date[1]);
                    monthCB.setSelectedIndex (month);
                    switch (date[2]) {
                        case "Year": yearCB.setSelectedIndex (0);;break;
                        case "2020": yearCB.setSelectedIndex (1);break;
                        case "2021": yearCB.setSelectedIndex (2);break;
                        case "2022": yearCB.setSelectedIndex (3);break;
                        case "2023": yearCB.setSelectedIndex (4);break;
                        case "2024": yearCB.setSelectedIndex (5);break;
                        
                    }
                    
                    
                    
                }
                output=parts[0]+"\t"+"\t"+parts[1]+"\t"+parts[2]+"\t"+parts[3]+"\t"+parts[4]+"\t"+parts[5]+"\t"+parts[6]+"\t"+parts[7]+"\t"+parts[8]+"\t"+parts[9];
                
              
            }
            outputTA.setText("Acoount Number\tOwner Name\tDate\tAddress\tArrears\tPMR\tCMR\tTotal Unit\tCurrent Charge\tTotal Bill\n");
            outputTA.append(output);
           found=true;
          
        }
       
    }
    if(found==false){
        JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); }
             
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); 
        } catch (IOException ex) {
            JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE); 
        }
        finally{
            try {
                fr.close ();
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_searchBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
          int accountNO=0;
        try{
             accountNO = Integer.parseInt (numberTF.getText());
            String date =" ";
            int monthInt=0;
            String month = (String) monthCB.getSelectedItem ( ) ;
            switch (month) {
                case "January": monthInt = 1;break;
                case "February": monthInt = 2;break;
                case "March": monthInt = 3;break;
                case "April": monthInt = 4;break;
                case "May": monthInt = 5;break;
                case "June": monthInt = 6;break;
                case "July": monthInt = 7;break;
                case "August": monthInt= 8;break;
                case "September": monthInt= 9;break;
                case "October": monthInt = 10;break;
                case "November": monthInt =11;break;
                case "December": monthInt = 12;break;
            }
            date=dayCB.getSelectedItem() +"/" +monthInt +"/" + (String) yearCB.getSelectedItem();
            String name = nameTF.getText ();
            String address = adressTA.getText ();
            double arrears=Double.parseDouble(arrearsTF.getText());
            double pmr=Double.parseDouble(pmrTF.getText());
            double cmr=Double.parseDouble(cmrTF.getText());

            double totalUnit=Double.parseDouble(totalUnitTF.getText());
            double currentCharge=Double.parseDouble(currentChargeTF.getText());
            double totalBill=Double.parseDouble(totalBillTF.getText());

            Electricity bill=new Electricity( accountNO, name,  address,  date,   arrears,  pmr,  cmr, totalUnit, currentCharge, totalBill);
            billList.add(bill);
            
            writeFile();
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Please ensure your input is in Integer format!",
                "ERROR", JOptionPane. ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
           int index;
        boolean found =false;
       
        for (Electricity d:billList) {
          if (d.getAcountNo()==accountNO){
          index = billList.indexOf(d);//indexOf s object in the bills arraylist
          
          billList.remove(index);//remove object from arrayList
          try{
        writeFile();
         }catch (Exception e) {
         System.out.println (e.getMessage ()) ;
         }
          JOptionPane.showMessageDialog(null, "The file is edited successfully.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);          found=true;
          break;
           }//if  
         }//for
        if(found==false)   
          JOptionPane.showMessageDialog (null, "The file can't be found",
                "ERROR", JOptionPane. ERROR_MESSAGE);  
    }//GEN-LAST:event_editBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adressTA;
    private javax.swing.JTextField arrearsTF;
    private javax.swing.JButton calculateBTN;
    private javax.swing.JTextField cmrTF;
    private javax.swing.JTextField currentChargeTF;
    private javax.swing.JLabel dateTM;
    private javax.swing.JComboBox<String> dayCB;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton diplayBTN;
    private javax.swing.JButton editBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField numberTF;
    private static javax.swing.JTextArea outputTA;
    private javax.swing.JTextField pmrTF;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField totalBillTF;
    private javax.swing.JTextField totalUnitTF;
    private javax.swing.JComboBox<String> yearCB;
    // End of variables declaration//GEN-END:variables
}
